#!/usr/bin/env bash

## config
[[ -e "$HOME/.config/aur.rc" ]] && {
	source "$HOME/.config/aur.rc"
}

cfg_work_dir="${cfg_work_dir:-$HOME/.aur}"
cfg_aur_url="${cfg_aur_url:-https://aur.archlinux.org}"
cfg_abs_tree="${cfg_abs_tree:-/var/abs}"
cfg_makepkg_flags='-rs'
cfg_libfbt_path="${cfg_libfbt_path:-/usr/lib/libfbt}"
# /config

[[ -e "$cfg_libfbt_path" ]] || {
	echo "This script depends on libfbt: https://github.com/fbt/libfbt"
	exit 1
}

source "${cfg_libfbt_path}/libfbt.sh"

aur.usage() {
	echo "$0 [options] [packages]"

	echo "SYNC (-S):"
	echo "-s|--search			# search"
	echo "-d|--download-only	# download only"
	echo "-u|--upgrade			# upgrade"
	echo "-y|--update			# update ABS"
	echo
	echo "OTHER:"
	echo "-a|--aur-only			# AUR only"
	echo "-h|--help				# show this message"
}

aur.args() {
	while [[ "$1" ]]; do
		case "$1" in
			-a|--aur-only) flag_aur_only='1';;
			-S|--sync) action_group='sync';;
			-s|--search) action='search';;
			-u|--upgrade) flag_upgrade='1';;
			-y|--update) flag_update='1';;

			-w|--download-only) flag_download_only='1';;
			-b|--build) flag_build='1';;
			-N|--noconfirm) flag_noconfirm='1';;
			-D|--asdeps) flag_asdeps='1';;
			-h|--help) aur.usage; exit;;
			--) :;;
			*) args+=( "$1" );;
		esac
		shift
	done
}

aur.get_package() {
#	local package_repo
	[[ "$flag_aur_only" ]] && {
		package_repo="`package-query --aur-url "$cfg_aur_url" -A "$1" | head -1 | cut -d '/' -f1`"
	} || {
		package_repo="`package-query --aur-url "$cfg_aur_url" -AS "$1" | head -1 | cut -d '/' -f1`"
	}

	[[ "$package_repo" ]] || {
		lf.err "Package $1 not found!\n"
		return 1
	}

	cd "$cfg_work_dir"

	case "${package_repo}" in
		aur)	
			lf.msg "Downloading $cfg_aur_url/packages/${1:0:2}/${1}/${1}.tar.gz\n"
			curl "$cfg_aur_url/packages/${1:0:2}/${1}/${1}.tar.gz" | gzip -d | tar xf - || {
				lf.err "Fail!\n"
				return 3
			}
		;;

		*)
			[[ "$flag_build" ]] && {
				cp -r "${cfg_abs_tree}/${package_repo}/${1}" . || {
					lf.err "Fail!\n"
					return 9
				}
			} || {
				[[ "$flag_download_only" ]] && {
					sudo pacman --cachedir "`pwd`" -Sw "$1"
				}
			}
		;;
	esac

	return 0
}

aur.update_local_db() {
	lf.msg "Updating ABS...\n"
	sudo abs >/dev/null || { lf.msg 'Fail!'; return 1; }

	sudo pacman -Sy || { return 1; }
}

aur.upgrade() {
	local old_pkgs
	old_pkgs=( `package-query -Au | cut -d ' ' -f1` )

	[[ "$flag_aur_only" ]] || { sudo pacman -Su; }

	lf.msg "Updating packages from AUR..."

	[[ "$old_pkgs" ]] || {
		lf.msg "Everything seems to be up to date."
		return 0
	}

	lf.msg "Packages that need updates: ${old_pkgs[*]}"
	read -n1 -p "Proceed? [Y/n] " answer
	[[ "$answer" == 'y' ]] || [[ "$answer" ]] && {
		echo
		lf.msg 'Ok.'
		return 1
	}

	for i in "${old_pkgs[@]}"; do
		"$BASH" "$0" -NS "$i" || {
			failed_pkgs+=( "$i" )
		}
	done

	[[ "$failed_pkgs" ]] && {
		lf.msg "Failed to upgrade the following pacages: ${failed_pkgs[*]}"
		return 1
	}

	return 0
}

aur.build_package() {
	local aur_deps

	cd "$cfg_work_dir/$package"
	[[ "$flag_build" ]] || { cfg_makepkg_flags+=' -i'; }
	[[ "$flag_noconfirm" ]] && { cfg_makepkg_flags+=' --noconfirm'; }

	source PKGBUILD

	for i in "${depends[@]}"; do
		package-query --aur-url "$cfg_aur_url" -A "$i" && {
			lf.msg "$package depends on $i, installing it"
			"$BASH" "$0" -aNS --asdeps "$i"
		}
	done

	makepkg ${cfg_makepkg_flags}
}

aur.search() {
	[[ "$flag_aur_only" ]] && {
		package-query --aur-url "$cfg_aur_url" -As "$1"
	} || {
		package-query --aur-url "$cfg_aur_url" -ASs "$1"
	}
}

aur.init() {
	for i in "$cfg_work_dir"; do
		[[ -e "$i" ]] || {
			mkdir -p "$i" || {
				lf.msg "Cannot create $i!"
				return 1
			}
		}
	done
}

aur.main() {
	aur.init || { return 1; }
	aur.args `lf.getopt "$@"` || { return 1; }

	package="${args[0]##*/}"

	case "$action_group" in
		sync)
			action="${action:-build}"

			[[ "$flag_update" ]] && { aur.update_local_db; }
			[[ "$flag_upgrade" ]] && { aur.upgrade; }

			[[ "$package" ]] && {
				case "$action" in
					search) aur.search "$package" || { return "$?"; };;
					build)
						aur.get_package "$package" || { return "$?"; }

						[[ "$flag_download_only" ]] || {
							case "$package_repo" in	
								aur)
									aur.build_package || { return "$?"; }
								;;

								*)
									[[ "$flag_build" ]] && {
										aur.build_package || { return "$?"; }
									} || {
										sudo pacman -S "$package"
									}
								;;
							esac
						}
					;;
				esac
			}
		;;

		*) sudo pacman "$@";;
	esac
}

aur.main "$@"
