#!/usr/bin/env bash
# Author: Jack L. Frost <fbt@fleshless.org>
# Licensed under the Internet Software Consortium (ISC) license.
# See LICENSE for its text.
set -eu

_self="${0##*/}"

# Config
client_id='7901fd66b0490c5'
tmp_dir='/tmp'

# Functions
echo() { printf '%s\n' "$*"; }
err() { echo "$*" >&2; }

debug() {
	(( "$flag_debug" )) && { err "DEBUG: $*"; }
	return 0
}

mktemp() {
	>"$1" || {
		err "Cannot create $1!"
		return 1
	}

	echo "$1"
}

usage() {
	while read; do printf '%s\n' "$REPLY"; done <<- EOF
		$_self is a relatively simple imgur client. It does not support authorization.

		Usage: $_self [flags] [path]
		Flags:
		    -h|--help          Show this message.
		    -s|--screenshot    Make a screenshot and upload that. If a path is specified, the screenshot is saved there.
		                         If the path is a dir, the screenshot will be saved under that directory with a random name.
		                         You can override the default tmp dir (/tmp) in the config file with \`tmp_dir=<path>\`
		    -F|--fullscreen    Make a fullscreen screenshot instead of asking you to select a window or an area. Implies -s.
		    -R|--remove-file   Remove the file after uploading. Applies to tmp files too.
		    -c|--config-file   Source an alternative config file.
			-d|--debug         Toggle debug messages.

		There is no support for putting the image URL into the X clipboard. That's stupid. Just do \`imgur | xclip\`.
		You can set some stuff in a config file. Look in the argument handling part of the script for details.
		The default path is \$HOME/.config/imgur.rc.sh
	EOF
}

depends() {
	type -P "$1" &>/dev/null || {
		err "$2"
		return 1
	}
}

set_argv() {
	declare arg opt c
	declare -ag ARGV

	while (( $# )); do
		unset -v arg opt c

		case "$1" in
			(--) ARGV+=( "$1" ); break;;

			(--*)
				IFS='=' read arg opt <<< "$1"
				ARGV+=( "$arg" )

				[[ "$opt" ]] && {
					ARGV+=( "$opt" )
				}
			;;

			(-*)
				while read -n1 c
				do
					case "$c" in
						-|'') :;;
						*) ARGV+=( "-$c" );;
					esac
				done <<< "$1"
			;;

			(*) ARGV+=( "$1" );;
		esac
		shift
	done
}

main() {
	local flag_screenshot=0 flag_fullscreen=0 flag_remove_file=0 flag_debug=0

	if [[ "${XDG_CONFIG_HOME-}" ]]; then
		cfg_file="${XDG_CONFIG_HOME}/imgur.rc.sh"
	else
		cfg_file="$HOME/.config/imgur.rc.sh"
	fi

	while (( $# )); do
		case "$1" in
			(--) shift; break;;

			(-h|--help) usage; return 0;;
			(-s|--screenshot) flag_screenshot=1;;
			(-F|--fullscreen)
				flag_screenshot=1
				flag_fullscreen=1
			;;

			(-R|--remove-file) flag_remove_file=1;;
			(-c|--config-file)
				cfg_file="$2"

				[[ -f "$cfg_file" ]] || {
					err "Config does not exist: ${cfg_file}"
					return 1
				}

				shift
			;;
			(-d|--debug) flag_debug=1;;

			(-*)
				err "Unknown key: $1"
				usage
				return 1
			;;

			(*) break;;
		esac
		shift
	done

	debug "${ARGV[@]}"

	if [[ -f "$cfg_file" ]]; then
		source "$cfg_file" || {
			err "Failed sourcing the config: ${cfg_file}"
			return 1
		}
	fi

	depends curl 'This script depends on curl to upload the files.' || return 1
	depends jshon 'This script depends on jshon to parse the API json output.' || return 1

	if (( "$flag_screenshot" )); then
		depends scrot 'The screenshot feature depends on scrot to grab the image.' || return 1

		(( $# )) && {
			if [[ -d "$1" ]]; then
				tmp_dir="$1"
			else
				file="$1"
			fi
		}

		[[ "${file-}" ]] || {
			file=$(mktemp "${tmp_dir}/scn_${RANDOM}.png")
		}

		(( "$flag_fullscreen" )) || {
			scrot_misc_options+=( '-s' )
		}

		debug "Saving the screenshot to ${file}"

		scrot -z ${scrot_misc_options[*]-} "$file" || {
			err "scrot failed"
			return 1
		}
	else
		(( $# )) || { usage; return 1; }
		file="$1"
	fi

	[[ -f "$file" ]] || {
		err "$file does not exist."
		return 1
	}

	api_answer=$(curl -sfH "Authorization: Client-ID $client_id" -F "image=@$file" "https://api.imgur.com/3/upload")
	curl_exit_code="$?"

	debug "$api_answer"

	if (( "$curl_exit_code" > 0 )); then
		err "Upload failed."
		return "$curl_exit_code"
	else
		api_status=$( jshon -e status -u <<< "$api_answer" )

		(( "$api_status" < 400 )) || {
			err "Upload failed. API says error: $api_status"
			return 1
		}

		img_url=$( jshon -e data -e link -u <<< "$api_answer" )
		echo "$img_url"
	fi

	(( "$flag_remove_file" )) && { rm -v "$file" >&2; }
}

set_argv "$@"
main "${ARGV[@]-}"
