#!/usr/bin/env bash
# Maintainer: Jack L. Frost <fbt@fleshless.org>
set -eu

_self="${0##*/}"
cfg_url="http://ix.io"

echo() { printf '%s\n' "$*"; }
err() { echo "$*" >&2; }

cat() { while read; do echo "$REPLY"; done }

usage() {
	cat <<- EOF
		Usage: ${_self} [flags] < <file>
		    Flags:
		        -h|--help            Show this message
		        -d|--delete <id>     Delete an id
		        -p|--put <id>        Overwrite an id
		        -l|--limit <num>     Number of times th paste can be read before it's deleted.
	EOF
}

main() {
	type -P curl &>/dev/null || {
		err "Can't find curl in your system; you need it for this script to work."
		return 1
	}

	[[ -f "$HOME/.config/ixio.rc" ]] && {
		if ! source "$HOME/.config/ixio.rc"; then
			_ec="$?"
			err "Failed to source the config at ${HOME}/.config/ixio.rc ($_ec)"
			return 1
		fi
	}

	while (( "$#" )); do
		case "$1" in
			--help|-h) usage; return 0;;

			--user|-u) cfg_username="$2"; shift;;
			--nologin|-n) flag_nologin=1;;

			--delete|-d) action='delete'; paste_id="$2"; shift;;
			--limit|-l) curl_options+=( '-F' "read:1=${2}" ); shift;;
			--put|-p) curl_options+=( '-X' 'PUT' ); paste_id="$2"; shift;;

			--) shift; break;;
			-*)
				err "Unknown key: $1"
				usage
				return 1
			;;
			*) break;;
		esac
		shift
	done

	if [[ -v cfg_username && ! -v flag_nologin ]]; then
		[[ -v cfg_password ]] || {
			err "no password provided, bailing."
			return 1
		}

		curl_options+=( '-u' "${cfg_username}:${cfg_password}" )
	fi

	action=${action:-"upload"}

	case "$action" in
		upload) curl ${curl_options[*]-} -F 'f:1=<-' "${cfg_url}/${paste_id-}";;
		delete) curl ${curl_options[*]-} -X DELETE "${cfg_url}/${paste_id}";;
	esac
}

main "$@"
