#!/usr/bin/env bash


echo() { printf '%s\n' "$*"; }
err() { echo "$*" >&2; }

usage() {
	echo "Usage: lockd [-r <rundir>] [-p <poll_rate>] <command>"
}

cleanup() {
	rm -f "$cfg_lockfile"
}

main() {
	if ! [[ "$XDG_RUNTIME_DIR" ]]; then
		XDG_RUNTIME_DIR="/run/user/$UID"
	fi

	cfg_poll_rate=3
	cfg_rundir="$XDG_RUNTIME_DIR"

	while (( $# )); do
		case "$1" in
			(-h|--help) usage; exit 0;;

			(-r|--run-dir) cfg_rundir=$2;;
			(-p|--poll-rate) cfg_poll_rate=$2;;

			(--) shift; break;;
			(*) break;;
		esac
		shift
	done

	cfg_lockfile="$cfg_rundir/lockd.lock"

	(( $# )) || {
		usage
		return 1
	}

	lock_cmd=( "$@" )

	[[ $(xssstate -s) == 'disabled' ]] && {
		err "Screensaver is disabled. Use xset s <seconds> to enable it."
		return 1
	}

	while sleep "$cfg_poll_rate"; do
		if ! [[ -f "$cfg_locker_lockfile" ]]; then
			time_left=$(( $(xssstate -t) / 1000 ))

			if ! (( time_left )); then
				> "$cfg_lockfile"
				"${lock_cmd[@]}"
			fi
		fi
	done
}

trap 'cleanup' EXIT

main "$@"
