#!/bin/bash
# Copyright (c) 2012 fbt <fbt@fleshless.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#   - Redistributions of source code must retain the above copyright notice, 
#       this list of conditions and the following disclaimer.
#   - Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

tmpdir="/tmp/mctmp"
mcdir="$HOME/.minecraf"
minecraft_jar="$HOME/.minecraft/bin/minecraft.jar"

miner.usage() { echo "Usage: `basename $0` [-j </path/to/jar>] <mod_archive>"; }
miner.msg() { echo "[miner] $1"; }
miner.err() { miner.msg "(error) $1" >&2; }

while getopts "j:h" option; do
	case "$option" in
		j) minecraft_jar=`realpath "$OPTARG"`;;
		s) flag_server='1';;
		h|?|*) miner.usage; exit 3;;
	esac
done

[[ "$OPTIND" ]] && { shift $[OPTIND-1]; }

mod_archive=`realpath "$1"`

[[ -d "$tmpdir" ]] && { rm -r "$tmpdir"; }

mkdir -p "$tmpdir"
cd "$tmpdir"

[[ -f "$mod_archive" ]] || { miner.err "$mod_archive does not exist"; exit 1; }

cp "$minecraft_jar" "${minecraft_jar}.backup"

miner.msg "Patching $minecraft_jar with ${mod_archive}... "

unzip "$minecraft_jar" &>/tmp/miner.log
rm "$minecraft_jar"
unzip -o "$mod_archive" &>>/tmp/miner.log
[[ "$flag_server" ]] || {
	[[ -d "META-INF" ]] && { rm -r META-INF; }
}
zip -r "$minecraft_jar" . &>>/tmp/miner.log

cd; rm -r "$tmpdir"

miner.msg "success"
