#!/bin/bash
# Copyright (c) 2012 fbt <fbt@fleshless.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#   - Redistributions of source code must retain the above copyright notice, 
#       this list of conditions and the following disclaimer.
#   - Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

tmpdir="/tmp/mctmp"
mcdir="$HOME/.minecraft"
current_dir="`pwd`"

miner.usage() {
	echo "Usage: `basename $0` [-d <minecraft_dir>] <mod>"
}

miner.msg() {
	echo "[miner] $1"
}

miner.err() {
	miner.msg "(error) $1" >&2
}

while getopts "d:h" option; do
	case "$option" in
		d) mcdir=`realpath "$OPTARG"`;;
		h|?|*) miner.usage; exit 3;;
	esac
done

[[ "$OPTIND" ]] && { shift $[OPTIND-1]; }

target_zip=`realpath "$1"`

[[ -d "$tmpdir" ]] && { rm -r "$tmpdir"; }

mkdir -p "$tmpdir"
cd "$tmpdir"

[[ -f "$target_zip" ]] || { miner.err "$target_zip does not exist"; exit 1; }

cp "$mcdir/bin/minecraft.jar" "$mcdir/bin/minecraft.jar.backup"

miner.msg "Patching ${mcdir}/bin/minecraft.jar with ${target_zip}... "

unzip "$mcdir/bin/minecraft.jar" &>/tmp/miner.log
rm "$mcdir/bin/minecraft.jar"
unzip -o "$target_zip" &>>/tmp/miner.log
[[ -d "META-INF" ]] && { rm -r META-INF; }
zip -r "$mcdir/bin/minecraft.jar" . &>>/tmp/miner.log

cd; rm -r "$tmpdir"

miner.msg "success"
