#!/usr/bin/bash

get_bookmarks() {
	while read url title; do
		echo "$url"
	done < "$HOME/.config/bookmarks"
}

main() {
	action=$1; shift

	case "${action}" in
		bmarks)
			uri=$(get_bookmarks | rofi -dmenu "$@")
			[[ "$uri" ]] && { sx-open "$uri"; }
			printf '%s\n' "$uri"
		;;
	esac
}

main "$@"
