#!/usr/bin/env bash

cfg_url='http://sprunge.us'

err() { printf '%s\n' "$1" >&2; }

main() {
	type -P curl &>/dev/null || {
		err "Can't find curl in your system; you need it for this script to work."
		return 1
	}

	curl -F 'sprunge=<-' "$cfg_url"
}

main "$@"
